
import {IconButtonProps} from '@material-ui/core/IconButton';
import MuiIconButton from '@material-ui/core/IconButton/IconButton';
import SvgIcon, {SvgIconProps} from '@material-ui/core/SvgIcon';
import React from 'react';

// Generated by IcoMoon.io
export const InfoIcon = (props: SvgIconProps) => {
  return (
    <SvgIcon {...props}>
      <path
        fillRule="nonzero"
        // tslint:disable-next-line:max-line-length
        d="M10.5 7.125c0-0.619 0.506-1.125 1.125-1.125h0.75c0.619 0 1.125 0.506 1.125 1.125v0.75c0 0.619-0.506 1.125-1.125 1.125h-0.75c-0.619 0-1.125-0.506-1.125-1.125v-0.75z"
      />
      <path
        fillRule="nonzero"
        // tslint:disable-next-line:max-line-length
        d="M15 18h-6v-1.5h1.5v-4.5h-1.5v-1.5h4.5v6h1.5z"
      />
      <path
        fillRule="nonzero"
        // tslint:disable-next-line:max-line-length
        d="M12 0c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zM12 21.75c-5.385 0-9.75-4.365-9.75-9.75s4.365-9.75 9.75-9.75 9.75 4.365 9.75 9.75-4.365 9.75-9.75 9.75z"
      />
    </SvgIcon>
  );
};

export const InfoIconButton = (props: IconButtonProps & {isActive: boolean}) => {
  const {isActive, disabled, ...rest} = props;
  return (
    <MuiIconButton
      color={isActive ? 'primary' : 'secondary'}
      disabled={disabled}
      disableRipple={true}
      {...rest}
    >
      <InfoIcon/>
    </MuiIconButton>
  );
};
