
import {IconButtonProps} from '@material-ui/core/IconButton';
import MuiIconButton from '@material-ui/core/IconButton/IconButton';
import SvgIcon, {SvgIconProps} from '@material-ui/core/SvgIcon';
import React from 'react';

// Generated by IcoMoon.io
export const SettingsIcon = (props: SvgIconProps) => {
  return (
    <SvgIcon {...props}>
      <path
        fillRule="nonzero"
        // tslint:disable-next-line:max-line-length
        d="M21.886 14.303c-1.259-2.181-0.502-4.976 1.691-6.246l-2.358-4.085c-0.674 0.395-1.457 0.622-2.293 0.622-2.52 0-4.563-2.057-4.563-4.594h-4.717c0.006 0.783-0.189 1.577-0.608 2.303-1.259 2.181-4.058 2.923-6.255 1.658l-2.358 4.085c0.679 0.386 1.267 0.951 1.685 1.675 1.257 2.178 0.504 4.967-1.681 6.24l2.358 4.085c0.671-0.391 1.451-0.615 2.283-0.615 2.512 0 4.55 2.044 4.563 4.569h4.717c-0.002-0.775 0.194-1.56 0.609-2.279 1.257-2.177 4.049-2.92 6.244-1.664l2.358-4.085c-0.675-0.386-1.258-0.949-1.674-1.669zM12 16.859c-2.684 0-4.859-2.176-4.859-4.859s2.176-4.859 4.859-4.859c2.684 0 4.859 2.176 4.859 4.859s-2.176 4.859-4.859 4.859z"
      />
    </SvgIcon>
  );
};

export const SettingsIconButton = (props: IconButtonProps & {isActive: boolean}) => {
  const {isActive, disabled, ...rest} = props;
  return (
    <MuiIconButton
      color={isActive ? 'primary' : 'secondary'}
      disabled={disabled}
      disableRipple={true}
      {...rest}
    >
      <SettingsIcon/>
    </MuiIconButton>
  );
};
